name: Build with jpackage

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Build client
        run: ./gradlew :client:clean :client:build

      - name: Run jpackage (Windows)
        if: runner.os == 'Windows'
        run: |
          jpackage --input client/build/libs --name "qbupdater 2" --icon "client/src/main/resources/lain.ico" --main-jar qbupdater.jar --main-class org.lain.qbupdater.QbUpdater --type exe --win-shortcut --win-menu

      - name: Run jpackage (Linux)
        if: runner.os == 'Linux'
        run: |
          jpackage --input client/build/libs --name "qbupdater 2" --icon "client/src/main/resources/lain.ico" --main-jar qbupdater.jar --main-class org.lain.qbupdater.QbUpdater --type deb --linux-shortcut --linux-menu-group "Utility"

      - name: Run jpackage (macOS)
        if: runner.os == 'macOS'
        run: |
          jpackage --input client/build/libs --name "qbupdater 2" --icon "client/src/main/resources/lain.ico" --main-jar qbupdater.jar --main-class org.lain.qbupdater.QbUpdater --type pkg

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: qbupdater-${{ runner.os }}
          path: |
            **/*.exe
            **/*.deb
            **/*.pkg